version: 2
jobs:
  build:
    working_directory: ~/test-ci-code
    docker:
      - image: circleci/node:10.14-browsers
    steps:
      - checkout
      - run:
          name: install
          command: 'npm install'
      - run:
          name: test:e2e
          command: 'npm run test:e2e:ci'
